language: android

addons: 
  code_climate:
    # https://codeclimate.com/github/amardeshbd/android-daily-headlines 
    repo_token: d930b549878b857fe0be9bf587bfd712c6bb93736e3a37b5fadc0f96185b5d3e

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.2

    # The SDK version used to compile your project
    - android-24
    
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

script: ./gradlew assembleDebug
